<?php
/**
 * @var $block \Razoyo\AnimalProfile\Block\Profile\Photo
 */
?>
<p><?= $block->escapeHtml($block->getGreeting()) ?></p>
<form class="form form-edit-animal-profile"
      action="<?= $block->escapeUrl($block->getSubmitUrl()) ?>"
      method="post" id="form-animal-profile"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <div data-bind="scope: 'animal.profile'" class="animal-profile">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "animal.profile": {
                    "component": "Razoyo_AnimalProfile/js/profile/view",
                    "animalOptions": <?= /* @noEscape */ $block->getAnimalOptionsJson() ?>,
                    "currentAnimal": "<?= /* @noEscape */ $block->getCurrentAnimal() ?>",
                    "photoBaseUrl": "<?= /* @noEscape */ $block->getPhotoUrl() ?>"
                }
            }
        }
    }
}
</script>
